# -*- coding: utf-8 -*-
"""Generates 100 striking, luxury, bilingual daily announcements for Kaftan Angelo."""

items = [
    # 1-10: Artisan Heritage & Craftsmanship
    ("1973 óta tökéletesített bőrműves hagyomány — Angelo mester műhelyéből Budapestre.",
     "Artisanal leathercraft refined since 1973 — from Master Angelo’s atelier to Budapest.",
     "/rolunk/", "/en/about/"),
    ("Több mint 20 éve a Kossuth Lajos utcában: a prémium bőrkabátok budapesti otthona.",
     "Over 20 years on Kossuth Lajos utca: the landmark home of handcrafted leather in Budapest.",
     "/uzlet/", "/en/visit/"),
    ("Egy igazi bőrkabát nem öregszik — minden viseléssel saját patinát és egyéni karaktert kap.",
     "Genuine leather never ages — it acquires a unique patina and timeless character with every wear.",
     "/utmutatok/valodi-bor-felismerese/", "/en/guides/how-to-tell-real-leather/"),
    ("Kézzel válogatott prémium alapanyagok: kollekciónk minden darabja egyedi műalkotás.",
     "Hand-selected premium hides: every piece in our collection is an individual work of art.",
     "/kollekciok/", "/en/collections/"),
    ("Lassú divat, örök érték: kabátjaink évtizedekig hűséges kísérői maradnak.",
     "Slow fashion, enduring value: our coats are crafted to stay with you for decades.",
     "/rolunk/", "/en/about/"),
    ("Fél évszázados mesterségbeli tudás: nálunk minden öltés mögött valódi szakértelem áll.",
     "Half a century of artisanal mastery: behind every stitch lies genuine expertise.",
     "/rolunk/", "/en/about/"),
    ("Nem sorozatgyártás, hanem kézműves gondosság minden egyes részletben.",
     "Not mass production, but artisanal devotion in every single detail.",
     "/kollekciok/", "/en/collections/"),
    ("Az igazi luxus a részletekben rejlik: prémium bélések és masszív, tartós cipzárak.",
     "True luxury lives in the details: premium linings and robust, durable hardware.",
     "/kollekciok/", "/en/collections/"),
    ("Angelo mester hitvallása: a valódi bőr természetes szépségét semmi sem pótolhatja.",
     "Master Angelo’s philosophy: nothing can replace the natural grace of genuine leather.",
     "/rolunk/", "/en/about/"),
    ("Örökség, amely nemzedékről nemzedékre száll — válasszon időtálló értéket.",
     "A heritage passed from generation to generation — choose timeless endurance.",
     "/rolunk/", "/en/about/"),

    # 11-20: Material Mastery (Lambskin, Cowhide, Nappa)
    ("Báránybőr vs. marhabőr: ismerje meg a vajpuha nappa és az ellenálló bőr különbségét.",
     "Lambskin vs. cowhide: discover the contrast between buttery nappa and rugged leather.",
     "/utmutatok/baranybor-marhabor-borkabat-osszehasonlitas/", "/en/guides/lambskin-vs-cowhide-leather-jacket/"),
    ("A bárány nappa bőr páratlan lágysága azonnal felveszi teste vonalát.",
     "The incomparable suppleness of lambskin nappa moulds instantly to your body.",
     "/utmutatok/baranybor-marhabor-borkabat-osszehasonlitas/", "/en/guides/lambskin-vs-cowhide-leather-jacket/"),
    ("A marhabőr tartása és ereje: kabát, amely a legzordabb időjárásnak is ellenáll.",
     "The resilience and structure of cowhide: a jacket that withstands the harshest weather.",
     "/utmutatok/baranybor-marhabor-borkabat-osszehasonlitas/", "/en/guides/lambskin-vs-cowhide-leather-jacket/"),
    ("Természetes lélegzés: a valódi bőr sosem fülled be, tökéletes hőérzetet biztosít.",
     "Natural breathability: genuine leather breathes with you, ensuring optimal temperature.",
     "/utmutatok/valodi-bor-felismerese/", "/en/guides/how-to-tell-real-leather/"),
    ("A bőr természetes illata és meleg tapintása összetéveszthetetlen védjegyünk.",
     "The unmistakable aroma and warm touch of genuine leather are our signature.",
     "/utmutatok/valodi-bor-felismerese/", "/en/guides/how-to-tell-real-leather/"),
    ("Anilin és félanilin felületek: hagyjuk érvényesülni a bőr természetes rajzolatát.",
     "Aniline and semi-aniline finishes: celebrating the authentic grain of natural hides.",
     "/utmutatok/valodi-bor-felismerese/", "/en/guides/how-to-tell-real-leather/"),
    ("A minőségi bőr idővel egyre szebb lesz — a patina az Ön közös történetét meséli el.",
     "Quality leather only improves with time — its patina tells your personal story.",
     "/rolunk/", "/en/about/"),
    ("Vízlepergető, mégis rugalmas: a megfelelően ápolt bőr évtizedekig védelmet nyújt.",
     "Supple yet water-repellent: properly conditioned leather protects for decades.",
     "/utmutatok/borkabat-apolas/", "/en/guides/leather-jacket-care/"),
    ("A báránybőr eleganciája tökéletes választás a tavaszi és őszi budapesti napokra.",
     "The understated elegance of lambskin: the ideal companion for Budapest spring and autumn.",
     "/noi-borkabatok/", "/en/womens-leather-jackets/"),
    ("Robusztus motoros fazonok prémium minőségű, válogatott bőrből férfiaknak.",
     "Robust biker cuts crafted from selected heavy leather for distinguished gentlemen.",
     "/ferfi-borkabatok/", "/en/mens-leather-jackets/"),

    # 21-30: Shearling (Irha) & Winter Warmth
    ("Toszkán irha: a természet legkiválóbb hőszigetelője a fagyos téli napokon.",
     "Tuscan shearling: nature’s superior thermal insulator for freezing winter days.",
     "/irhakabatok/", "/en/shearling-jackets/"),
    ("Egy irhakabátban nincs szüksége vastag pulóverre: a természetes gyapjú ölelése melegít.",
     "No heavy layers needed beneath shearling: natural wool creates a microclimate of warmth.",
     "/irhakabatok/", "/en/shearling-jackets/"),
    ("Kívül selymes velúr, belül puha gyapjú — fedezze fel kézzel varrt irhakabátjainkat.",
     "Silky suede on the outside, plush wool within — explore our handcrafted shearling coats.",
     "/irhakabatok/", "/en/shearling-jackets/"),
    ("Hogyan válasszunk irhakabátot? Szakértői kalauzunk segít a döntésben.",
     "How to choose the ideal shearling coat? Our expert guide walks you through every step.",
     "/utmutatok/bor-irha-szorme-osszehasonlitas/", "/en/guides/leather-shearling-fur-comparison/"),
    ("Az irha kabát könnyedebb, mint gondolná — a modern kikészítés kényelmet és meleget ad.",
     "Modern shearling is remarkably lightweight — advanced tanning gives effortless comfort.",
     "/irhakabatok/", "/en/shearling-jackets/"),
    ("Hóesésben és metsző szélben is védelmet nyújt: a valódi toszkán irha ereje.",
     "Shielding against snow and biting winds: the undeniable resilience of genuine shearling.",
     "/irhakabatok/", "/en/shearling-jackets/"),
    ("Irhabélésű kapucnik és magas gallérok: stílusos védelem a budapesti telekben.",
     "Shearling hoods and storm collars: stylish protection tailored for Budapest winters.",
     "/irhakabatok/", "/en/shearling-jackets/"),
    ("Férfi irhadzsekik aviátor stílusban: a klasszikus pilótadzsekik örök eleganciája.",
     "Men’s shearling aviator jackets: the timeless ruggedness of classic flight jackets.",
     "/irhakabatok/", "/en/shearling-jackets/"),
    ("Női irhabundák és karcsúsított irhakabátok: nőies vonalak hideg időben is.",
     "Women’s tailored shearling coats: feminine silhouettes designed for cold weather.",
     "/irhakabatok/", "/en/shearling-jackets/"),
    ("Az irhakabát ápolása egyszerű, ha ismeri a megfelelő mozdulatokat — olvassa el tanácsainkat.",
     "Caring for shearling is simple when you know the right technique — read our practical guide.",
     "/utmutatok/irhakabat-apolas/", "/en/guides/shearling-coat-care/"),

    # 31-40: Fur & Luxury Outerwear (Szőrme)
    ("A szőrmekabátok örök eleganciája: nemes szőrmék gondos szabással és béléssel.",
     "The eternal grace of fine fur: noble pelts tailored with refined linings.",
     "/szormekabatok/", "/en/fur-coats/"),
    ("Szőrmemellények: sokoldalú luxus darabok ősztől tavaszig bármilyen összeállításhoz.",
     "Fur vests: versatile luxury layers pairing effortlessly from autumn through spring.",
     "/szormekabatok/", "/en/fur-coats/"),
    ("Hogyan tároljuk a szőrmekabátot nyáron? Tartsa meg szőrméje fényét és puhaságát.",
     "How to store fur coats in summer? Preserve luster and softness through warm seasons.",
     "/utmutatok/szormekabat-tarolas/", "/en/guides/fur-coat-storage/"),
    ("Soha ne tárolja szőrméjét műanyag zsákban: a természetes szálaknak lélegezniük kell.",
     "Never store fine fur in airtight plastic: natural pelts need breathable cotton garment bags.",
     "/utmutatok/szormekabat-tarolas/", "/en/guides/fur-coat-storage/"),
    ("Bőr és szőrme kombinációk: modern dizájn és klasszikus luxus találkozása.",
     "Leather and fur combinations: where contemporary design meets classic luxury.",
     "/kollekciok/", "/en/collections/"),
    ("A szőrme természetes hőszabályozása: könnyű viselet maximális védelemmel.",
     "Natural thermal balance of genuine fur: light to wear with peerless protection.",
     "/szormekabatok/", "/en/fur-coats/"),
    ("Kifinomult gallér- és mandzsettamegoldások a budapesti szőrmekollekciónkban.",
     "Refined collar and cuff detailing across our curated Budapest fur collection.",
     "/szormekabatok/", "/en/fur-coats/"),
    ("Bőr, irha vagy szőrme? Segítünk kiválasztani az életstílusához legjobban illőt.",
     "Leather, shearling, or fur? Let us help you find the match for your lifestyle.",
     "/utmutatok/bor-irha-szorme-osszehasonlitas/", "/en/guides/leather-shearling-fur-comparison/"),
    ("A természetes szőrme selymessége semmilyen szintetikus műszőrmével nem vetekedhet.",
     "The organic silkiness of authentic fur cannot be matched by synthetic alternatives.",
     "/szormekabatok/", "/en/fur-coats/"),
    ("Professzionális tisztítás és karbantartás: bízza ránk kabátja megóvását.",
     "Professional cleaning and preservation: trust our atelier with your garment’s longevity.",
     "/utmutatok/szormekabat-tarolas/", "/en/guides/fur-coat-storage/"),

    # 41-55: Bespoke Tailoring & Made-to-Measure (Egyedi rendelés)
    ("Egyedi méretre készítés: az Ön pontos testméreteire szabott, kompromisszummentes kabát.",
     "Made-to-measure tailoring: a bespoke jacket crafted to your precise measurements.",
     "/egyedi-rendeles/", "/en/custom-orders/"),
    ("Tökéletes ujjhossz és vállszélesség: ne elégedjen meg a konfekcióméretekkel.",
     "Flawless sleeve length and shoulder pitch: never settle for standard off-the-rack sizing.",
     "/egyedi-rendeles/", "/en/custom-orders/"),
    ("Válassza ki a bőrt, a színt és a bélést — mi megvalósítjuk elképzelését.",
     "Select your hide, hue, and lining — our atelier will bring your vision to reality.",
     "/egyedi-rendeles/", "/en/custom-orders/"),
    ("Hogyan zajlik az egyedi bőrkabát készítésének folyamata? Ismerje meg a lépéseket.",
     "How does custom leather jacket tailoring work? Discover our step-by-step bespoke process.",
     "/utmutatok/egyedi-borkabat-rendeles/", "/en/guides/custom-leather-jacket-order/"),
    ("Személyes méretvétel és konzultáció Angelo mester műhelyében a belvárosban.",
     "Personal fitting and consultation at Master Angelo’s atelier in downtown Budapest.",
     "/egyedi-rendeles/", "/en/custom-orders/"),
    ("Kedvenc kabátja elkopott? Hozza el hozzánk, és elkészítjük az új, prémium változatát.",
     "Is your vintage favourite worn out? Bring it in, and we will tailor an exact premium replica.",
     "/egyedi-rendeles/", "/en/custom-orders/"),
    ("Méretre igazítás és professzionális bőrjavítás: leheljen új életet kedvenc darabjába.",
     "Expert alterations and repairs: breathe fresh life into your cherished leather garments.",
     "/egyedi-rendeles/", "/en/custom-orders/"),
    ("Az egyedi rendelés nem felár, hanem befektetés egy életre szóló tökéletes viseletbe.",
     "Bespoke is not an indulgence — it is an investment in a lifelong, faultless fit.",
     "/egyedi-rendeles/", "/en/custom-orders/"),
    ("Extra méretek és egyedi igények: nálunk nincsenek lehetetlen szabásvonalak.",
     "Extended sizing and custom proportions: our cutters accommodate every physique effortlessly.",
     "/egyedi-rendeles/", "/en/custom-orders/"),
    ("Gombok, cipzárak és rejtett zsebek: szabja személyre kabátja legapróbb részleteit is.",
     "Hardware, fasteners, and interior pockets: customise every nuance of your bespoke outerwear.",
     "/egyedi-rendeles/", "/en/custom-orders/"),
    ("Hozzon fényképet az álomkabátjáról — megtervezzük és kézzel elkészítjük Önnek.",
     "Bring a picture of your dream silhouette — we will pattern and handcraft it for you.",
     "/egyedi-rendeles/", "/en/custom-orders/"),
    ("Bőrkabát javítás és cipzárcsere eredeti olasz alkatrészekkel a Kossuth Lajos utcában.",
     "Leather alterations and zipper replacement using genuine Italian components in Budapest.",
     "/egyedi-rendeles/", "/en/custom-orders/"),
    ("Az egyedi kalapálás és varrás művészete: évtizedes tapasztalat minden öltésben.",
     "The heritage of benchcraft leather tailoring: decades of refined intuition in every stitch.",
     "/egyedi-rendeles/", "/en/custom-orders/"),
    ("Kérjen időpontot személyes próbára WhatsAppon keresztül néhány másodperc alatt.",
     "Book your private fitting appointment on WhatsApp in just a few seconds.",
     "https://wa.me/36203593216", "https://wa.me/36203593216"),
    ("Ön megálmodja, Angelo mester megalkotja: kézműves bőrszabászat kompromisszumok nélkül.",
     "You envision it, Master Angelo crafts it: artisan leather tailoring without compromise.",
     "/egyedi-rendeles/", "/en/custom-orders/"),

    # 56-70: Leather Care & Connoisseur Tips (Bőrápolás & felismerés)
    ("Hogyan ismerhető fel a valódi bőr? A pórusok természetes egyenetlensége a minőség jele.",
     "How to tell genuine leather? The organic irregularity of pores is the hallmark of authenticity.",
     "/utmutatok/valodi-bor-felismerese/", "/en/guides/how-to-tell-real-leather/"),
    ("Megázott a bőrkabátja? Szárítsa szobahőmérsékleten, soha ne tegye radiátor közelébe.",
     "Caught in the rain? Dry your leather coat at room temperature, never next to direct heat radiators.",
     "/utmutatok/borkabat-apolas/", "/en/guides/leather-jacket-care/"),
    ("Használjon széles fa vállfát: megvédi a kabát vállívét a deformálódástól.",
     "Always use a broad contoured wooden hanger: it preserves your jacket’s shoulder line.",
     "/utmutatok/borkabat-apolas/", "/en/guides/leather-jacket-care/"),
    ("A bőr balzsamozása évente egyszer megóvja a kiszáradástól és repedezéstől.",
     "Conditioning your leather once a year prevents drying and keeps fibres supple for life.",
     "/utmutatok/borkabat-apolas/", "/en/guides/leather-jacket-care/"),
    ("A tűzteszt és a vízcsepp-teszt: a valódi bőr és a műbőr megkülönböztetésének titkai.",
     "Water drop and breath tests: the expert methods for distinguishing genuine hides from synthetic PU.",
     "/utmutatok/valodi-bor-felismerese/", "/en/guides/how-to-tell-real-leather/"),
    ("A műbőr megreped és lehámlik — a valódi bőr évtizedekig nemesedik és szépül.",
     "Faux leather peels and flakes — genuine leather matures gracefully over decades.",
     "/utmutatok/valodi-bor-felismerese/", "/en/guides/how-to-tell-real-leather/"),
    ("Hogyan távolítsuk el az apró foltokat anélkül, hogy károsítanánk a bőr felületét?",
     "How to lift light surface spots without harming delicate leather grain? Read our guide.",
     "/utmutatok/borkabat-apolas/", "/en/guides/leather-jacket-care/"),
    ("A velúr és nubuk különleges bánásmódot igényel: használjon speciális krepkefét.",
     "Suede and nubuck require dedicated care: a crepe brush restores natural pile texture.",
     "/utmutatok/borkabat-apolas/", "/en/guides/leather-jacket-care/"),
    ("A bőrkabát méretének kiválasztása: hogyan kell állnia a mellkasnál és a karoknál?",
     "Choosing jacket size: how should leather drape across the chest and upper arms?",
     "/utmutatok/borkabat-meret-utmutato/", "/en/guides/leather-jacket-fit-guide/"),
    ("A valódi bőr a test melegétől meglágyul és finoman idomul viselőjéhez.",
     "Genuine leather gently warms with body heat and moulds softly to your natural posture.",
     "/utmutatok/valodi-bor-felismerese/", "/en/guides/how-to-tell-real-leather/"),
    ("Soha ne használjon acetont vagy erős vegyszert valódi bőr tisztítására.",
     "Never use acetone or harsh domestic solvents on premium leather finishes.",
     "/utmutatok/borkabat-apolas/", "/en/guides/leather-jacket-care/"),
    ("A bőr természetes olajai megérdemlik a táplálást: prémium méhviaszos ápolószerek.",
     "Preserve natural oils: high-grade beeswax creams protect without clogging pores.",
     "/utmutatok/borkabat-apolas/", "/en/guides/leather-jacket-care/"),
    ("Hogyan tárolja kabátját szezonon kívül? A pormentes, hűvös és száraz hely a kulcs.",
     "Off-season storage: keep your leather outerwear in a cool, dark, and well-ventilated space.",
     "/utmutatok/borkabat-apolas/", "/en/guides/leather-jacket-care/"),
    ("A bőr finom illata az igazi kézművesség védjegye — kerülje az illatosított szintetikus spray-ket.",
     "The rich aroma of cured leather is a badge of authenticity — avoid artificial sprays.",
     "/utmutatok/valodi-bor-felismerese/", "/en/guides/how-to-tell-real-leather/"),
    ("Kérdése van egy régebbi bőrkabátja felújításáról? Szívesen segítünk szakvéleménnyel.",
     "Have questions about restoring a vintage leather jacket? Our atelier provides expert appraisals.",
     "/egyedi-rendeles/", "/en/custom-orders/"),

    # 71-85: Budapest Lifestyle & Shopping Guide (Budapesti életstílus)
    ("Budapesti bőrkabát vásárlási kalauz: miért érdemes az V. kerület szívében vásárolni?",
     "Budapest leather shopping guide: why explore our District V boutique in the historic core?",
     "/utmutatok/budapesti-borkabat-vasarlasi-kalauz/", "/en/guides/budapest-leather-shopping-guide/"),
    ("Az Astoria és a Ferenciek tere között: könnyen megközelíthető belvárosi elegancia.",
     "Between Astoria and Ferenciek tere: centrally located elegance with effortless transit.",
     "/uzlet/", "/en/visit/"),
    ("Séta a Kossuth Lajos utcán: fedezze fel Budapest tradicionális divatutcáját.",
     "Strolling down Kossuth Lajos utca: experience one of Budapest’s most historic fashion avenues.",
     "/uzlet/", "/en/visit/"),
    ("Hűvös esték a Duna partján: egy finom nappa bőrkabát a tökéletes kísérő.",
     "Brisk evenings along the Danube: a supple nappa jacket provides the ideal layer.",
     "/noi-borkabatok/", "/en/womens-leather-jackets/"),
    ("Budapesti téli napok: a toszkán irha megbízható védelmet nyújt a szeles utcákon.",
     "Crisp Budapest winter days: Tuscan shearling gives dependable comfort on breezy avenues.",
     "/irhakabatok/", "/en/shearling-jackets/"),
    ("Nemzetközi látogatóink kedvence: a kézműves európai bőrművesség Budapesten.",
     "A favourite among international travellers: handcrafted European leathercraft in Budapest.",
     "/en/guides/budapest-outerwear-shopping/", "/en/guides/budapest-outerwear-shopping/"),
    ("Kérjen tanácsot szakértőinktől az üzletben — több évtizedes tapasztalattal segítünk.",
     "Consult with our in-store specialists — decades of hands-on experience at your service.",
     "/uzlet/", "/en/visit/"),
    ("Adómentes vásárlás (Tax-Free) az EU-n kívülről érkező látogatóknak.",
     "Tax-free shopping assistance available for visitors travelling from outside the European Union.",
     "/uzlet/", "/en/visit/"),
    ("Budapest és a divat: miért a minőségi bőrkabát a városi elegancia alapköve?",
     "Budapest and outerwear: why a quality leather jacket remains the cornerstone of urban elegance.",
     "/utmutatok/budapesti-kabatvasarlas/", "/en/guides/budapest-outerwear-shopping/"),
    ("Látogasson el hozzánk egy kötelezettségmentes próbára a Kossuth Lajos u. 18. alá.",
     "Drop by for a relaxed fitting at Kossuth Lajos u. 18 — no appointment required during open hours.",
     "/uzlet/", "/en/visit/"),
    ("Nyitvatartás: Hétfőtől péntekig 10:00–19:00, szombaton 10:00–17:00 között várjuk.",
     "Boutique hours: Monday to Friday 10:00–19:00, Saturday 10:00–17:00.",
     "/uzlet/", "/en/visit/"),
    ("Közvetlen parkolási és metrólehetőségek a belvárosi Kaftan Angelo üzletnél.",
     "Convenient parking and central metro access (M2, M3) right by the Kaftan Angelo boutique.",
     "/uzlet/", "/en/visit/"),
    ("Kóstoljon bele a tradicionális budapesti vendégszeretetbe üzletünkben.",
     "Enjoy warm, attentive boutique hospitality whenever you visit our Budapest showroom.",
     "/uzlet/", "/en/visit/"),
    ("Ajándékozzon örök értéket: prémium bőrkesztyűk, övek és pénztárcák a kínálatunkban.",
     "Gift timeless refinement: handcrafted leather gloves, belts, and wallets in our collection.",
     "/kollekciok/", "/en/collections/"),
    ("Készleten lévő modellek azonnali méretigazítása a helyszínen szakértő szabónktól.",
     "On-site minor alterations available on selected in-stock models by our master tailor.",
     "/egyedi-rendeles/", "/en/custom-orders/"),

    # 86-100: Sustainable Luxury & Direct Boutique Service
    ("A fenntarthatóság legszebb formája: egyetlen minőségi darab, amely évtizedekig kitart.",
     "The essence of sustainable luxury: one heirloom garment that outlasts decades of trends.",
     "/rolunk/", "/en/about/"),
    ("Mondjon nemet az eldobható divatra — válassza a valódi bőrt és a tartós zanaatkultúrát.",
     "Reject disposable fast-fashion — choose authentic leather and generational craft culture.",
     "/rolunk/", "/en/about/"),
    ("Egy jó bőrkabát olyan, mint a jó bor: az idő múlásával csak gazdagabbá válik.",
     "A distinguished leather jacket is like fine wine: time only deepens its character.",
     "/rolunk/", "/en/about/"),
    ("A klasszikus fekete bőrdzseki soha nem megy ki a divatból — fedezze fel fazonjainkat.",
     "The classic black leather jacket is perpetually in style — explore our iconic silhouettes.",
     "/ferfi-borkabatok/", "/en/mens-leather-jackets/"),
    ("Elegáns női bőrmellények és karcsúsított zakók a hétköznapi magabiztosságért.",
     "Sophisticated women’s leather blazers and vests tailored for effortless confidence.",
     "/noi-borkabatok/", "/en/womens-leather-jackets/"),
    ("Finom szőrmekiegészítők: kényeztető melegség és luxus a mindennapokban.",
     "Fine fur collars and cold-weather accents: indulgent warmth for your everyday wardrobe.",
     "/szormekabatok/", "/en/fur-coats/"),
    ("Több száz elégedett vásárló Európa és a világ minden tájáról 2004 óta.",
     "Hundreds of distinguished clients across Europe and worldwide served since 2004.",
     "/rolunk/", "/en/about/"),
    ("Minden kérdésére készséggel válaszolunk telefonon: +36 1 266 7274.",
     "We are delighted to answer your questions by phone: +36 1 266 7274.",
     "tel:+3612667274", "tel:+3612667274"),
    ("Gyors üzenetváltás és képküldés közvetlenül a WhatsApp ügyfélszolgálatunkon.",
     "Instant messaging and photo inquiries available via our dedicated WhatsApp support.",
     "https://wa.me/36203593216", "https://wa.me/36203593216"),
    ("Kövesse budapesti mindennapjainkat és új modelljeinket az Instagramon is.",
     "Follow our Budapest boutique life and new seasonal creations on Instagram.",
     "https://www.instagram.com/kaftanangelo.budapest/", "https://www.instagram.com/kaftanangelo.budapest/"),
    ("A tökéletes ajándék: kézzel varrt bőr kiegészítők valódi minőségi garanciával.",
     "The discerning gift: benchmade leather accessories backed by our hallmark of quality.",
     "/kollekciok/", "/en/collections/"),
    ("Partnerprogram utazásszervezőknek és idegenvezetőknek: fedezzük fel együtt a budapesti divatot.",
     "Partner program for concierges and tour specialists: showcasing Budapest’s finest outerwear.",
     "/partnerprogram/", "/en/partners/"),
    ("Egyedi hímzés és monogramozás lehetősége a megrendelt bőrkabátok belső zsebébe.",
     "Custom embroidery and personal monogramming options available inside bespoke jackets.",
     "/egyedi-rendeles/", "/en/custom-orders/"),
    ("Kaftan Angelo: ahol a török bőrműves hagyomány találkozik a budapesti eleganciával.",
     "Kaftan Angelo: where Ottoman leather mastery meets classic Budapest sophistication.",
     "/rolunk/", "/en/about/"),
    ("Lépjen be az időtálló bőrdzsekik világába — szeretettel várjuk a Kossuth Lajos u. 18-ban.",
     "Step into the enduring world of fine leathercraft — we warmly welcome you at Kossuth Lajos u. 18.",
     "/uzlet/", "/en/visit/")
]

print(f"Total crafted announcements: {len(items)}")

# Generate TypeScript file
ts_content = '''// 100 striking, luxury, bilingual daily announcements for Kaftan Angelo.
// Rotated daily on the top announcement bar with a 10-day non-repeating guarantee.

export interface AnnouncementItem {
  id: number;
  hu: string;
  en: string;
  url_hu: string;
  url_en: string;
}

export const announcements: AnnouncementItem[] = [
'''

for idx, (hu, en, url_hu, url_en) in enumerate(items, 1):
    hu_esc = hu.replace("'", "\\'")
    en_esc = en.replace("'", "\\'")
    ts_content += f"  {{ id: {idx}, hu: '{hu_esc}', en: '{en_esc}', url_hu: '{url_hu}', url_en: '{url_en}' }},\n"

ts_content += '''];

// Deterministic 100-day cycle shuffle ensuring no item repeats within 100 consecutive days
export const announcementCycle: number[] = [
  42, 17, 88, 3, 61, 29, 94, 12, 75, 5,
  83, 36, 19, 58, 91, 7, 72, 24, 49, 14,
  68, 33, 97, 8, 52, 21, 80, 15, 63, 2,
  77, 45, 10, 86, 31, 66, 18, 93, 27, 4,
  55, 38, 89, 13, 70, 22, 99, 35, 60, 9,
  82, 48, 16, 73, 26, 95, 41, 6, 85, 30,
  64, 20, 98, 39, 54, 11, 78, 25, 90, 44,
  1, 67, 34, 87, 23, 56, 40, 92, 100, 50,
  74, 28, 62, 46, 81, 37, 71, 57, 96, 47,
  65, 32, 79, 43, 84, 53, 69, 59, 76, 51
];
'''

with open("src/data/announcements.ts", "w", encoding="utf-8") as f:
    f.write(ts_content)

print("src/data/announcements.ts written successfully.")
